version: '3.8'

services:
  mongodb:
    image: 'saneag/mongo:latest'
  backend:
    image: 'saneag/backend:latest'
    ports:
      - '5000:5000'

    depends_on:
      - mongodb

  frontend:
    image: 'saneag/frontend:latest'
    ports:
      - '3000:3000'
    stdin_open: true
    restart: always
    build:
      context: .
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
