version: "3.8"

services:
  mongodb:
    image: "saneag/mongo"
    volumes:
      - "data:/data/db"
  backend:
    image: "saneag/backend"
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - ./server:/uploads
      - /app/node_modules

    depends_on:
      - mongodb

  frontend:
    image: "saneag/frontend"
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
